esphome:
  name: reefgenie
  friendly_name: Reefgenie

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ReefGenie Fallback Hotspot"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret webserver_username
    password: !secret webserver_password
    
external_components:
  - source:
      type: local
      path: components
    components: [reefgenie]

i2c:
  sda: GPIO21
  scl: GPIO22

reefgenie:
  id: tankgenie
  valve_id: valve # 
  pump_id: pump
  sleep_pin: # Sleep pin for both the valve and pump stepper motor, these are shared to save pins on the ESP32
    number: GPIO23
    inverted: true

stepper:
  - platform: a4988
    id: valve
    step_pin: GPIO19
    dir_pin:
      number: GPIO18
      inverted: false
    max_speed: 500 steps/s
  - platform: a4988
    id: pump
    step_pin: GPIO17
    dir_pin:
      number: GPIO16
      inverted: false
    max_speed: 500 steps/s

sensor:
  - platform: reefgenie
    current_drops_counted:
      id: current_drops_counted
      name: Current Drops Counted
    calcium_tested:
      id: calcium_tested
      name: Calcium
    alkalinity_tested:
      id: alkalinity_tested
      name: Alkalinity
  - platform: adc
    pin: GPIO32
    name: "Drop Sensor"
    update_interval: 50ms
    filters:
      - clamp:
          min_value: 0.8
          max_value: 1.0
          ignore_out_of_range: true
      - delta: 0.05

text_sensor:
  - platform: reefgenie
    current_status:
      id: current_status
      name: Current Status
    current_operation:
      id: current_step
      name: Current Operation

# i2c:
#   sda: GPIO21
#   scl: GPIO22

# sensor:
#   - platform: tcs34725
#     red_channel:
#       name: "TCS34725 Red Channel"
#     green_channel:
#       name: "TCS34725 Green Channel"
#     blue_channel:
#       name: "TCS34725 Blue Channel"
#     clear_channel:
#       name: "TCS34725 Clear Channel"
#     illuminance:
#       name: "TCS34725 Illuminance"
#     color_temperature:
#       name: "TCS34725 Color Temperature"
#     glass_attenuation_factor: 1.0
#     update_interval: 10s
#     address: 0x29


globals:
  - id: valve_actuator_pos # Integer for storing the stepper position in case of reboot
    type: "int"
    restore_value: yes
    initial_value: '0'

button:
  - platform: template
    name: "Test Calcium"
    id: test_calcium
    on_press:
      - reefgenie.test_calcium: tankgenie
    

# control the led on the TCS34725 colorimeter
# output:
#   - platform: ledc
#     pin: GPIO15
#     id: gpio_15

# light:
#   - platform: monochromatic
#     output: gpio_15
#     name: "Sensor Light"

