[wokwi]
version = 1
elf = ".esphome/build/reefgenie/.pioenvs/reefgenie/firmware.elf"
firmware = ".esphome/build/reefgenie/.pioenvs/reefgenie/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"
